In [72]:
!pip install requests beautifulsoup4

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

In [73]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from datetime import datetime

In [74]:
url = "http://www.amis.pk/daily%20market%20changes.aspx"

response = requests.get(url)
print("Status Code:", response.status_code)

Status Code: 200

In [75]:
soup = BeautifulSoup(response.text, "html")
print (soup)

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta content="Agriculture Commodity Daily Prices in Punjab Pakistan, Grains,Vegetables,Fruit Prices,rice,wheat,sugarcane,cotton,potato,tomato,ginger,garlic,groundnut,white grain, black grain,mash,moong, masoor puls,mango,apple,grapes,banana" name="keywords"/>
<meta content="www.amis.pk" name="copyright"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<link href="css/w3.css" rel="stylesheet" type="text/css"/><link href="css/StyleSheet.css" rel="stylesheet" type="text/css"/>
<script src="js/global.js" type="text/javascript"></script>
<meta content="Daily Price Change,Punjab Pakistan,Fruit,vegetable and grain market" name="description"/>
<meta content="Agriculture,Agriculture Marketing,Punjab,Pakistan,Price Change,Daily Price,Grain,Fruit,Vegetable,Market Price,Mandi,Mundi,Onion,Garlic,Ginger,Rice,Cotton,Wheat,Corn,Maize,Black Grain,White Grain,Pulses,Mash,Masoor,Mango,Orange,Watermallon" name="keywords"/>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66071340-1', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript">
         function price_addelement() {

             var eleprice = document.getElementById("Prices");


             if (eleprice.style.display == "block") {
                 eleprice.style.display = "none";

             } else {
                 if (document.getElementById("pub1").style.display == "block" || document.getElementById("stakeholder").style.display == "block" || document.getElementById("import").style.display == "block") {
                     document.getElementById("pub1").style.display = "none";
                     document.getElementById("stakeholder").style.display = "none";
                     document.getElementById("import").style.display = "none";
                     // document.getElementById("contacts").style.display = "none"
                 }
                 eleprice.style.display = "block";

             }
             //alert(myUL);
         }

         function pub() {



             var i;
             var ele = document.getElementById("pub1");


             if (ele.style.display == "block") {
                 ele.style.display = "none";
             } else {
                 if (document.getElementById("Prices").style.display == "block" || document.getElementById("stakeholder").style.display == "block" || document.getElementById("import").style.display == "block") {
                     document.getElementById("Prices").style.display = "none";
                     document.getElementById("stakeholder").style.display = "none";
                     document.getElementById("import").style.display = "none";
                     //   document.getElementById("contacts").style.display = "none"
                 }

                 ele.style.display = "block";
             }



         }

         function stake() {




             var stakeele = document.getElementById("stakeholder");


             if (stakeele.style.display == "block") {
                 stakeele.style.display = "none";
             } else {

                 if (document.getElementById("Prices").style.display == "block" || document.getElementById("pub1").style.display == "block" || document.getElementById("import").style.display == "block") {
                     document.getElementById("Prices").style.display = "none";
                     document.getElementById("pub1").style.display = "none";
                     document.getElementById("import").style.display = "none";
                     //document.getElementById("contacts").style.display = "none"
                 }
                 stakeele.style.display = "block";
             }



         }

            function stat() {




                var contactele = document.getElementById("stats");


                if (contactele.style.display == "block") {
                    contactele.style.display = "none";
                } else {

                            if (document.getElementById("Prices").style.display == "block" || document.getElementById("pub1").style.display == "block" || document.getElementById("import").style.display == "block" || document.getElementById("stakeholder").style.display == "block") {
                    document.getElementById("Prices").style.display = "none";
                    document.getElementById("pub1").style.display = "none";
                    document.getElementById("import").style.display = "none";
                    document.getElementById("stakeholder").style.display = "none"
                }
                    contactele.style.display = "block";
                }



            }
         function importe() {




             var contactele = document.getElementById("import");


             if (contactele.style.display == "block") {
                 contactele.style.display = "none";
             } else {
                 if (document.getElementById("Prices").style.display == "block" || document.getElementById("pub1").style.display == "block" ) {
                     document.getElementById("Prices").style.display = "none";
                     document.getElementById("pub1").style.display = "none";
                     document.getElementById("contacts").style.display = "none";
                     //document.getElementById("stakeholder").style.display = "none"
                 }
                 contactele.style.display = "block";
             }



         }
        </script>
<style>
* {
  box-sizing: border-box;
}

.row::after {
  content: "";
  clear: both;
  display: table;
}

[class*="col-"] {
  float: left;
  padding: 05px;
}

html {
  font-family: "Lucida Sans", sans-serif;
}

.header {
  background-color: #9933cc;
  color: #ffffff;
  padding: 05px;
}

.menu ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
}



.aside {
  background-color: #33b5e5;
  padding: 05px;
  color: #ffffff;
  text-align: center;
  font-size: 14px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
}

.footer {
  background-color: #0099cc;
  color: #ffffff;
  text-align: center;
  font-size: 12px;
  padding: 00px;
}

/* For mobile phones: */
[class*="col-"] {
  width: 100%;
}

@media only screen and (min-width: 550px) {
  /* For tablets: */
  .col-s-1 {width: 8.33%;}
  .col-s-2 {width: 16.66%;}
  .col-s-3 {width: 25%;}
  .col-s-4 {width: 33.33%;}
  .col-s-5 {width: 41.66%;}
  .col-s-6 {width: 50%;}
  .col-s-7 {width: 58.33%;}
  .col-s-8 {width: 66.66%;}
  .col-s-9 {width: 75%;}
  .col-s-10 {width: 83.33%;}
  .col-s-11 {width: 91.66%;}
  .col-s-12 {width: 100%;}
}
@media only screen and (min-width: 800px) {
  /* For desktop: */
  .col-1 {width: 8.33%;}
  .col-2 {width: 16.66%;}
  .col-3 {width: 25%;}
  .col-4 {width: 33.33%;}
  .col-5 {width: 41.66%;}
  .col-6 {width: 50%;}
  .col-7 {width: 58.33%;}
  .col-8 {width: 66.66%;}
  .col-9 {width: 75%;}
  .col-10 {width: 83.33%;}
  .col-11 {width: 91.66%;}
  .col-12 {width: 100%;}
}
</style>
<title>
	Daily Price Commodity Change
</title>
</head><body id="home">
<script language="javascript" src="AJAX/CommunityBar.ashx" type="text/javascript">
</script>
<form action="./daily market changes.aspx" id="aspnetForm" method="post" name="aspnetForm">

In [76]:
table = soup.find("table")
rows = table.find_all("tr")

print(f"✅ Found {len(rows)} rows")

✅ Found 623 rows

In [77]:
soup.find('table')

<table border="0" cellpadding="4" cellspacing="0" id="ctl00_cphPage_GridView1">
<tr bgcolor="#1C5E55">
<th align="left" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$CityName')"><font color="White">CityName</font></a></b></font></th><th align="left" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$CropName')"><font color="White">CropName</font></a></b></font></th><th align="left" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$Today\'s FQP/Average Price')"><font color="White">Today's FQP/Average Price</font></a></b></font></th><th align="left" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$Yesterday\'s FQP/Average Price')"><font color="White">Yesterday's FQP/Average Price</font></a></b></font></th><th align="right" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$Change in Price')"><font color="White">Change in Price</font></a></b></font></th><th scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$Change in Price')"><font color="White">Price Direction</font></a></b></font></th>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Lahore</font></td><td><font color="#333333">Brinjal</font></td><td><font color="#333333">6050</font></td><td><font color="#333333">6450</font></td><td align="right"><font color="#333333"> -400</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Lahore</font></td><td><font color="#333333">Cauliflower</font></td><td><font color="#333333">4600</font></td><td><font color="#333333">4100</font></td><td align="right"><font color="#333333"> +500</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Lahore</font></td><td><font color="#333333">Cucumber (Kheera)</font></td><td><font color="#333333">4600</font></td><td><font color="#333333">4100</font></td><td align="right"><font color="#333333"> +500</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Lahore</font></td><td><font color="#333333">Watermelon</font></td><td><font color="#333333">5100</font></td><td><font color="#333333">5550</font></td><td align="right"><font color="#333333"> -450</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Lahore</font></td><td><font color="#333333">Green Chilli</font></td><td><font color="#333333">9750</font></td><td><font color="#333333">10250</font></td><td align="right"><font color="#333333"> -500</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Faisalabad</font></td><td><font color="#333333">Onion</font></td><td><font color="#333333">5750</font></td><td><font color="#333333">5200</font></td><td align="right"><font color="#333333"> +550</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Faisalabad</font></td><td><font color="#333333">Tomato</font></td><td><font color="#333333">7200</font></td><td><font color="#333333">6750</font></td><td align="right"><font color="#333333"> +450</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Faisalabad</font></td><td><font color="#333333">Spinach</font></td><td><font color="#333333">2650</font></td><td><font color="#333333">2500</font></td><td align="right"><font color="#333333"> +150</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Faisalabad</font></td><td><font color="#333333">Lady Finger/Okra (بھنڈی توری)</font></td><td><font color="#333333">18500</font></td><td><font color="#333333">19500</font></td><td align="right"><font color="#333333"> -1000</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Faisalabad</font></td><td><font color="#333333">Garlic (Local)</font></td><td><font color="#333333">14500</font></td><td><font color="#333333">17500</font></td><td align="right"><font color="#333333"> -3000</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Faisalabad</font></td><td><font color="#333333">Cucumber (Kheera)</font></td><td><font color="#333333">4750</font></td><td><font color="#333333">3800</font></td><td align="right"><font color="#333333"> +950</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Faisalabad</font></td><td><font color="#333333">Melon</font></td><td><font color="#333333">8600</font></td><td><font color="#333333">8750</font></td><td align="right"><font color="#333333"> -150</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Faisalabad</font></td><td><font color="#333333">Turmeric Whole(ثابت ہلدی)</font></td><td><font color="#333333">8550</font></td><td><font color="#333333">8750</font></td><td align="right"><font color="#333333"> -200</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Faisalabad</font></td><td><font color="#333333">Tindian</font></td><td><font color="#333333">5750</font></td><td><font color="#333333">6050</font></td><td align="right"><font color="#333333"> -300</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Gujranwala</font></td><td><font color="#333333">Onion</font></td><td><font color="#333333">6250</font></td><td><font color="#333333">5300</font></td><td align="right"><font color="#333333"> +950</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Gujranwala</font></td><td><font color="#333333">Bitter Gourd (کریلا)</font></td><td><font color="#333333">15900</font></td><td><font color="#333333">15800</font></td><td align="right"><font color="#333333"> +100</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Gujranwala</font></td><td><font color="#333333">Cauliflower</font></td><td><font color="#333333">4800</font></td><td><font color="#333333">4600</font></td><td align="right"><font color="#333333"> +200</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Gujranwala</font></td><td><font color="#333333">Peas</font></td><td><font color="#333333">9300</font></td><td><font color="#333333">8150</font></td><td align="right"><font color="#333333"> +1150</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Gujranwala</font></td><td><font color="#333333">Cucumber (Kheera)</font></td><td><font color="#333333">5100</font></td><td><font color="#333333">4500</font></td><td align="right"><font color="#333333"> +600</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Gujranwala</font></td><td><font color="#333333">Fenugreek(میتھی)</font></td><td><font color="#333333">5900</font></td><td><font color="#333333">5300</font></td><td align="right"><font color="#333333"> +600</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Okara</font></td><td><font color="#333333">Mash Pulse(Imported) washed</font></td><td><font color="#333333">39750</font></td><td><font color="#333333">41750</font></td><td align="right"><font color="#333333"> -2000</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Okara</font></td><td><font color="#333333">Maize</font></td><td><font color="#333333">8350</font></td><td><font color="#333333">8395</font></td><td align="right"><font color="#333333"> -45</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Okara</font></td><td><font color="#333333">Potato Fresh</font></td><td><font color="#333333">1175</font></td><td><font color="#333333">1100</font></td><td align="right"><font color="#333333"> +75</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Okara</font></td><td><font color="#333333">Onion</font></td><td><font color="#333333">5750</font></td><td><font color="#333333">5250</font></td><td align="right"><font color="#333333"> +500</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Okara</font></td><td><font color="#333333">Bitter Gourd (کریلا)</font></td><td><font color="#333333">13750</font></td><td><font color="#333333">14750</font></td><td align="right"><font color="#333333"> -1000</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Okara</font></td><td><font color="#333333">Carrot</font></td><td><font color="#333333">2750</font></td><td><font color="#333333">3250</font></td><td align="right"><font color="#333333"> -500</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Okara</font></td><td><font color="#333333">Banana(DOZEN)</font></td><td><font color="#333333">218</font></td><td><font color="#333333">225</font></td><td align="right"><font color="#333333"> -7</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Okara</font></td><td><font color="#333333">Bottle Gourd (کدو)</font></td><td><font color="#333333">7250</font></td><td><font color="#333333">7750</font></td><td align="right"><font color="#333333"> -500</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Okara</font></td><td><font color="#333333">sugarcane(گنڈ یری)</font></td><td><font color="#333333">11750</font></td><td><font color="#333333">9750</font></td><td align="right"><font color="#333333"> +2000</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Sargodha</font></td><td><font color="#333333">Onion</font></td><td><font color="#333333">5750</font></td><td><font color="#333333">5150</font></td><td align="right"><font color="#333333"> +600</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Sargodha</font></td><td><font color="#333333">Tomato</font></td><td><font color="#333333">7150</font></td><td><font color="#333333">6750</font></td><td align="right"><font color="#333333"> +400</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Sargodha</font></td><td><font color="#333333">Cauliflower</font></td><td><font color="#333333">4750</font></td><td><font color="#333333">4400</font></td><td align="right"><font color="#333333"> +350</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Sargodha</font></td><td><font color="#333333">Garlic (Local)</font></td><td><font color="#333333">14500</font></td><td><font color="#333333">17500</font></td><td align="right"><font color="#333333"> -3000</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Sargodha</font></td><td><font color="#333333">Cucumber (Kheera)</font></td><td><font color="#333333">4250</font></td><td><font color="#333333">3800</font></td><td align="right"><font color="#333333"> +450</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Sargodha</font></td><td><font color="#333333">Green Chilli</font></td><td><font color="#333333">7750</font></td><td><font color="#333333">7250</font></td><td align="right"><font color="#333333"> +500</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Rawalpindi</font></td><td><font color="#333333">Onion</font></td><td><font color="#333333">7950</font></td><td><font color="#333333">6150</font></td><td align="right"><font color="#333333"> +1800</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Rawalpindi</font></td><td><font color="#333333">Tomato</font></td><td><font color="#333333">7950</font></td><td><font color="#333333">7050</font></td><td align="right"><font color="#333333"> +900</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Rawalpindi</font></td><td><font color="#333333">Brinjal</font></td><td><font color="#333333">6350</font></td><td><font color="#333333">6600</font></td><td align="right"><font color="#333333"> -250</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Rawalpindi</font></td><td><font color="#333333">Bitter Gourd (کریلا)</font></td><td><font color="#333333">13150</font></td><td><font color="#333333">14050</font></td><td align="right"><font color="#333333"> -900</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/red-down.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Rawalpindi</font></td><td><font color="#333333">Cauliflower</font></td><td><font color="#333333">6150</font></td><td><font color="#333333">5700</font></td><td align="right"><font color="#333333"> +450</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Rawalpindi</font></td><td><font color="#333333">Radish</font></td><td><font color="#333333">2950</font></td><td><font color="#333333">2500</font></td><td align="right"><font color="#333333"> +450</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Rawalpindi</font></td><td><font color="#333333">Carrot</font></td><td><font color="#333333">6150</font></td><td><font color="#333333">5700</font></td><td align="right"><font color="#333333"> +450</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">
<td><font color="#333333">Rawalpindi</font></td><td><font color="#333333">Guava</font></td><td><font color="#333333">13150</font></td><td><font color="#333333">12750</font></td><td align="right"><font color="#333333"> +400</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="White">
<td><font color="#333333">Rawalpindi</font></td><td><font color="#333333">Cabbage</font></td><td><font color="#333333">5250</font></td><td><font color="#333333">4750</font></td><td align="right"><font color="#333333"> +500</font></td><td align="center"><font color="#333333"><img align="absmiddle" alt="Rise in price" border="0" height="11" src="/images/green-up.png" width="10"/></font></td>
</tr><tr bgcolor="#E3EAEB">

In [78]:
heading=table.find_all('th')
print (heading)

[<th align="left" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$CityName')"><font color="White">CityName</font></a></b></font></th>, <th align="left" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$CropName')"><font color="White">CropName</font></a></b></font></th>, <th align="left" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$Today\'s FQP/Average Price')"><font color="White">Today's FQP/Average Price</font></a></b></font></th>, <th align="left" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$Yesterday\'s FQP/Average Price')"><font color="White">Yesterday's FQP/Average Price</font></a></b></font></th>, <th align="right" scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$Change in Price')"><font color="White">Change in Price</font></a></b></font></th>, <th scope="col"><font color="White"><b><a href="javascript:__doPostBack('ctl00$cphPage$GridView1','Sort$Change in Price')"><font color="White">Price Direction</font></a></b></font></th>]

In [79]:
heading_titles=[title.text for title in heading]
print (heading_titles)

['CityName', 'CropName', "Today's FQP/Average Price", "Yesterday's FQP/Average Price", 'Change in Price', 'Price Direction']

In [80]:
df=pd.DataFrame(columns=heading_titles)
df

Empty DataFrame
Columns: [CityName, CropName, Today's FQP/Average Price, Yesterday's FQP/Average Price, Change in Price, Price Direction]
Index: []

In [81]:
rows = table.find_all("tr")

In [82]:
for row in rows[1:]:
  row_data=row.find_all('td')
  individual_row_data=[data.text.strip() for data in row_data]

  length=len(df)
  df.loc[length]=individual_row_data

In [83]:
df

,CityName,CropName,Today's FQP/Average Price,Yesterday's FQP/Average Price,Change in Price,Price Direction
0,Lahore,Brinjal,6050,6450,-400,
1,Lahore,Cauliflower,4600,4100,+500,
2,Lahore,Cucumber (Kheera),4600,4100,+500,
3,Lahore,Watermelon,5100,5550,-450,
4,Lahore,Green Chilli,9750,10250,-500,
...,...,...,...,...,...,...
617,Taunsasharif,Ginger (Thai),26500,27500,-1000,
618,Taunsasharif,Garlic (Local),13750,15500,-1750,
619,Taunsasharif,Cucumber (Kheera),3750,3800,-50,
620,Taunsasharif,Lemon (China),7500,6500,+1000,
621,Taunsasharif,Dates(Irani),46750,46500,+250,

In [84]:
df = df.drop(columns=['Price Direction'])
display(df.head())

,CityName,CropName,Today's FQP/Average Price,Yesterday's FQP/Average Price,Change in Price
0,Lahore,Brinjal,6050,6450,-400
1,Lahore,Cauliflower,4600,4100,+500
2,Lahore,Cucumber (Kheera),4600,4100,+500
3,Lahore,Watermelon,5100,5550,-450
4,Lahore,Green Chilli,9750,10250,-500

In [89]:
df.to_csv("marketwatch_mandi_prices.csv")

In [90]:
from google.colab import files

files.download("marketwatch_mandi_prices.csv")